import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  safelist: [
    // Green
    "bg-green-100",
    "bg-green-200",
    "bg-green-300",
    "bg-green-400",
    "bg-green-500",
    "bg-green-600",
    "bg-green-700",
    "bg-green-800",
    "bg-green-900",
    "hover:bg-green-100",
    "hover:bg-green-200",
    "hover:bg-green-300",
    "hover:bg-green-400",
    "hover:bg-green-500",
    "hover:bg-green-600",
    "hover:bg-green-700",
    "hover:bg-green-800",
    "hover:bg-green-900",
    "text-green-100",
    "text-green-200",
    "text-green-300",
    "text-green-400",
    "text-green-500",
    "text-green-600",
    "text-green-700",
    "text-green-800",
    "text-green-900",

    // Blue
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-300",
    "bg-blue-400",
    "bg-blue-500",
    "bg-blue-600",
    "bg-blue-700",
    "bg-blue-800",
    "bg-blue-900",
    "hover:bg-blue-100",
    "hover:bg-blue-200",
    "hover:bg-blue-300",
    "hover:bg-blue-400",
    "hover:bg-blue-500",
    "hover:bg-blue-600",
    "hover:bg-blue-700",
    "hover:bg-blue-800",
    "hover:bg-blue-900",
    "text-blue-100",
    "text-blue-200",
    "text-blue-300",
    "text-blue-400",
    "text-blue-500",
    "text-blue-600",
    "text-blue-700",
    "text-blue-800",
    "text-blue-900",

    // Gray
    "bg-gray-100",
    "bg-gray-200",
    "bg-gray-300",
    "bg-gray-400",
    "bg-gray-500",
    "bg-gray-600",
    "bg-gray-700",
    "bg-gray-800",
    "bg-gray-900",
    "hover:bg-gray-100",
    "hover:bg-gray-200",
    "hover:bg-gray-300",
    "hover:bg-gray-400",
    "hover:bg-gray-500",
    "hover:bg-gray-600",
    "hover:bg-gray-700",
    "hover:bg-gray-800",
    "hover:bg-gray-900",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",

    // Red
    "bg-red-100",
    "bg-red-200",
    "bg-red-300",
    "bg-red-400",
    "bg-red-500",
    "bg-red-600",
    "bg-red-700",
    "bg-red-800",
    "bg-red-900",
    "hover:bg-red-100",
    "hover:bg-red-200",
    "hover:bg-red-300",
    "hover:bg-red-400",
    "hover:bg-red-500",
    "hover:bg-red-600",
    "hover:bg-red-700",
    "hover:bg-red-800",
    "hover:bg-red-900",
    "text-red-100",
    "text-red-200",
    "text-red-300",
    "text-red-400",
    "text-red-500",
    "text-red-600",
    "text-red-700",
    "text-red-800",
    "text-red-900",

    // Orange
    "bg-green-600",
    "hover:bg-green-700",
    "text-white",
    "bg-blue-600",
    "hover:bg-blue-700",
    "bg-orange-500",
    "hover:bg-orange-600",
    "bg-red-600",
    "hover:bg-red-700",
    "bg-gray-200",
    "text-gray-500",

    // Yellow
    "bg-yellow-100",
    "bg-yellow-200",
    "bg-yellow-300",
    "bg-yellow-400",
    "bg-yellow-500",
    "bg-yellow-600",
    "bg-yellow-700",
    "bg-yellow-800",
    "bg-yellow-900",
    "hover:bg-yellow-100",
    "hover:bg-yellow-200",
    "hover:bg-yellow-300",
    "hover:bg-yellow-400",
    "hover:bg-yellow-500",
    "hover:bg-yellow-600",
    "hover:bg-yellow-700",
    "hover:bg-yellow-800",
    "hover:bg-yellow-900",
    "text-yellow-100",
    "text-yellow-200",
    "text-yellow-300",
    "text-yellow-400",
    "text-yellow-500",
    "text-yellow-600",
    "text-yellow-700",
    "text-yellow-800",
    "text-yellow-900",

    // White and black (se necessário)
    "text-white",
    "bg-white",
    "text-black",
    "bg-black",
  ],
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
